alias edit='idea.bat -e myfile.txt'
alias ncal='"C:\Users\kyto\nepcal.exe"'
alias pyobfuscate='pyo'
alias pymr='python manage.py runserver'
alias pym='python manage.py'
alias dja='django-admin'
alias hist='history'
alias pat='php artisan tinker'
alias phps='php -S localhost:8000 -t'
alias tmp='cd /tmp'
alias dnfconf='sudo micro /etc/dnf/dnf.conf'
alias pas='php artisan serve'
alias pa='php artisan'

# archives
alias ltar='tar -tvf'
alias mktar='tar -czf'
alias xtar='tar -xvf'

# random
alias d='cd "C:\Users\kyto\Desktop"'
alias dl='cd "C:\Users\kyto\Downloads"'
# alias conf='micro /home/kyto/.zshrc'
alias conf='micro "C:\Users\kyto\.bashrc"'
alias e='explorer'
# alias n='micro /home/kyto/Zz/notes.md'

# shortforms
alias h='htop'
alias s='sudo'
alias g='git'
alias py='python'
alias j='java'
alias jc='javac'
alias du='du -sh'
alias df='df -h'
alias gc='git clone'
alias gs='git status'
alias ga='git add'
alias glo='git log --oneline'
alias gls='git ls-files'
alias ka='killall'
alias l='ls -lhAF'
alias ssctl='sudo systemctl'

# tools
alias aa='aria2c -c -x5 -s10 -m0 --summary-interval 0'
alias enc='gpg -c --no-symkey-cache --cipher-algo AES256'
alias m='micro'
alias sm='sudo micro'
alias myip='curl https://ipinfo.io/ip'
alias play='mpv * --shuffle --no-video'
alias rmmeta='exiftool -all= '
alias ssss='scrcpy'
alias no='firejail --net=none'
alias fuck='termtyper'
alias r='gnirehtet autorun'

# yt-dlp
# yt-dlp -f 22 --playlist-start X --playlist-end Y LINK
alias y='yt-dlp --extract-audio --audio-format best'
alias yy='yt-dlp -f 22'
alias yymax='yt-dlp -f bestvideo+bestaudio'
alias yw='mpv --ytdl-format="[height=360]"'
